# ==============================================================================
# sites.yaml — Configuration for Change Detection System
# ==============================================================================
# Purpose: Configuration file for site monitoring
# ==============================================================================

sites:
  judiciary_uk:
    name: 'Judiciary UK'
    url: 'https://www.judiciary.uk/'
    sitemap_url: 'https://www.judiciary.uk/sitemap_index.xml'
    is_sitemap_index: true

  waverley_gov:
    name: 'Waverley Borough Council'
    url: 'https://www.waverley.gov.uk/'
    sitemap_url: 'https://www.waverley.gov.uk/sitemap.xml'
    is_sitemap_index: false