sites:
  judiciary_uk:
    is_sitemap_index: true
    last_processed: null
    name: Judiciary UK
    onboarded: true
    onboarding_datetime: 2025-08-09 16:19:28.508037
    sitemap_url: https://www.judiciary.uk/sitemap_index.xml
    status: onboarded
    top_urls:
    - https://www.judiciary.uk/news/
    - https://www.judiciary.uk/judgments/
    - https://www.judiciary.uk/press-releases/
    - https://www.judiciary.uk/consultations/
    - https://www.judiciary.uk/about-the-judiciary/
    url: https://www.judiciary.uk/
  waverley_gov:
    is_sitemap_index: false
    last_processed: null
    name: Waverley Borough Council
    onboarded: false
    onboarding_datetime: null
    sitemap_url: https://www.waverley.gov.uk/sitemap.xml
    status: not_onboarded
    top_urls: []
    url: https://www.waverley.gov.uk/
